### PR TITLE
update call to appium-android-driver params

### PR DESCRIPTION
**Pull request by vrunoa**
I made a fix to the call to the unlock method since we change it on `appium-android-driver`. 
Please review @jlipps @imurchie

### CODE REVIEW

**Comment by imurchie** [comment]
Looks good to me. You might want to bump the version in `package.json` so that it is known to be compatible (I guess we should have made that a breaking change in the android driver, eh?).

**Comment by mykola-mokhnach** [comment]
@imurchie Do we have functional tests implemented  for UIAutomator2? This had to be visible then if we do.

**Comment by vrunoa** [comment]
I didnt know a change on `appium-android-driver` would break this package. 
Maybe we should document this or trigger tests for this package when something change on `appium-android-driver`

**Comment by SrinivasanTarget** [comment]
Is everything fine here. If so can this be merged and a new version been published please? @imurchie @jlipps

**Comment by SrinivasanTarget** [comment]
@imurchie Can you publish a new version please? Or anything left related to this PR?

**Comment by imurchie** [comment]
Published as `appium-uiautomator2-driver@0.3.0`.

**Comment by SrinivasanTarget** [comment]
Thanks @imurchie 👍

**Pull request merged**
