### PR TITLE
Revert "createSession should return session's capabilities"

### PR DESCRIPTION
**Pull request by dpgraham**
Reverts appium/appium-uiautomator2-driver#157

### CODE REVIEW

**Comment by imurchie** [comment]
I don't think this is necessary.

**Comment by dpgraham** [comment]
This reverts it back to it's previous state? Are you saying reverting is unnecessary, or the original PR was unnecessary?

**Comment by imurchie** [comment]
I think in this case the original commit was correct. There is more info in `this.caps` than `caps`. At least to my tests. But each driver has been implemented differently. I think we should go through the drivers and make sure that we are returning the complete info. 

As it stands base driver slaps a bunch of info into `this.caps` that is not in `caps`.  The sub classes then sometimes deal in `caps` and sometimes in `this.caps`.

**Comment by imurchie** [comment]
`appium-xcuitest-driver`, `appium-uiautomator2-driver`, `appium-android-driver`, `appium-ios-driver` all seem ok in their current state, to my eye.

**Pull request closed without merging**
