### PR TITLE
feat: Update android-driver

### PR DESCRIPTION
**Pull request by mykola-mokhnach**

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@KazuCocoa Could you please run ruby client suite on this PR, so we could confirm the refactoring changes work as expected and I did not miss anything?

**Comment by KazuCocoa** [comment]
Running as https://github.com/appium/ruby_lib_core/pull/520
let me see how it will be

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-uiautomator2-driver/pull/720#issuecomment-1909326162 was fine. Failures I found was unstable emulator on CI related only

**Review by jlipps — COMMENTED** [review]
nice refactor!

**Pull request merged**
