### PR TITLE
Update getAttribute logic for boolean attributes

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Please merge it after https://github.com/appium/appium-uiautomator2-server/pull/56 is merged and published

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
@jlipps Exactly. This is the way it is defined in the spec

**Comment by jlipps** [comment]
I am still confused. The end state for a client using the driver looks same as it was before this set of changes. What is the point?

**Comment by mykola-mokhnach** [comment]
@jlipps Read https://github.com/appium/appium/issues/8321

**Comment by jlipps** [comment]
OK I get it now. I had read that, and thought that this change was turning strings into bool for every endpoint. But what I now see this is doing is keeping things bool that were bool and were supposed to be bool, and now letting the string through for the getElementAttribute call. I was confused because now the real change here is in a part of the code which is _not_ in the diff :-)

**Pull request merged**
