### PR TITLE
feat: add all the types

### PR DESCRIPTION
**Pull request by boneskull**
- uses TS instead of babel
- adds the usual tooling (no renovate)

this depends on appium/appium#18817 and appium/appium-android-driver#819.

- all mixins were changed to be object literals.
- because of the high levels of confusion around the capability objects being built in `createSession`, I renamed some of the methods it calls and attempted to otherwise make things more clear.  `createSession` returns an object which is a _superset_ of the user-defined capabilities, since it adds a bunch of device info.  see `lib/types.ts` for the type definitions of these objects; `createSession` responds with a capabilities object of type `Uiautomator2SessionCaps`
- renamed `fillDeviceDetails` to `getDeviceDetails` and hopefully made it faster by running the async operations in parallel.
- `initUiautomator2Server` returns the `Uiautomator2Server` instance (which we consume) so we know the value is defined. otherwise it still mutates the instance.
 
classes can use the `CreateResult` type argument when extending `BaseDriver` and implementing `ExternalDriver` to resolve with a custom value; if unset, the returned capabilities will contain only props as defined in the driver's constraints (plus any "base" constraints).

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* master
  * **PR #635** <a href="https://app.graphite.dev/github/pr/appium/appium-uiautomator2-driver/635" target="_blank">Graphite</a>  👈
    * **PR #636** <a href="https://app.graphite.dev/github/pr/appium/appium-uiautomator2-driver/636" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/appium/appium-uiautomator2-driver/635?utm_source=stack-comment).

**Comment by boneskull** [comment]
- all mixins were changed to be object literals.
- because of the high levels of confusion around the capability objects being built in `createSession`, I renamed some of the methods it calls and attempted to otherwise make things more clear.  `createSession` returns an object which is a _superset_ of the user-defined capabilities, since it adds a bunch of device info.  see `lib/types.ts` for the type definitions of these objects; `createSession` responds with a capabilities object of type `Uiautomator2SessionCaps`

**Comment by mykola-mokhnach** [comment]
I cannot review the PR, - it's too big 🤷 
In such case I usually merge yolo style and then monitor for possible issues to quickly fix them

**Comment by jlipps** [comment]
OK @mykola-mokhnach I merged in master and made all the required fixes. Let's see what tests say.

**Comment by jlipps** [comment]
tests seem reasonably ok. propose that we merge and cut a beta release and get people to test it out

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
@jlipps Yes, lets do it. Do you also have a similar PR for Espresso?

**Comment by jlipps** [comment]
@mykola-mokhnach no, nothing for Espresso yet. We'll need to work on that one from scratch. Or does it rely on the uia2 driver at all? Also, I am on PTO monday so I don't think it's a good idea for me to merge and publish. I'm also not sure if there is some kind of auto release script on this repo. Do you want to handle the mechanics of the beta release?

**Comment by mykola-mokhnach** [comment]
> @mykola-mokhnach no, nothing for Espresso yet. We'll need to work on that one from scratch. Or does it rely on the uia2 driver at all? Also, I am on PTO monday so I don't think it's a good idea for me to merge and publish. I'm also not sure if there is some kind of auto release script on this repo. Do you want to handle the mechanics of the beta release?

This repo has autorelease based on conventional commits (e.g. PR title and description).
Espresso driver does not have anything to do with UIA2 one, although I think it for sure makes sense to also update it if we want to release v6 of the android driver. Otherwise it will stop getting shared updates.

It makes sense to release the driver if you are around, so please do it before you know you will be available for a while.

**Comment by pavlo-dot-dev** [comment]
I have error "Error: Failed to create session. A new session could not be created. Details: 'app' can't be blank" on this version, when i try make session.

**Comment by pavlo-dot-dev** [comment]
https://github.com/appium/appium-uiautomator2-driver/pull/641 is actually problem in this version

**Comment by mykola-mokhnach** [comment]
@pavlo-dot-dev Please report your issue to the appropriate tracker and add the environment info plus server logs

**Comment by steven-george-neurovalens** [comment]
Disclaimer - First time poster - @boneskull I tried to move from uiautomator2@2.29.9 to the latest (uiautomator2@2.43.4) this version appears to be where driver.executeScript("mobile: deviceInfo", "networks") starts throwing errors for me. Was this collateral or an unreported issue? Sorry if it's been previous addressed I did try to look and search and didn't find any mention.

**Comment by KazuCocoa** [comment]
`mobile: deviceInfo` itself expects to have no arguments. What about removing "networks"? The response could have network info etc -> https://github.com/appium/appium-uiautomator2-driver?tab=readme-ov-file#mobile-deviceinfo
(potentially old implementation accepted arguments but ignored internally)

**Comment by steven-george-neurovalens** [comment]
@KazuCocoa thanks for steer - shouldn't really have needed it but here we are - taking out "networks" got me back what I used to use / needs. Thanks!

**Pull request merged**
