### PR TITLE
fix: change errant uiautomation2 reference

### PR DESCRIPTION
**Pull request by imurchie**
Fixes https://github.com/appium/appium/issues/13471

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
the actual automation backend in set before we know anything about the device, so we cannot automatically adjust the value depending on the target device if you are talking about that.

**Comment by imurchie** [comment]
I don't understand. Your logs are for an attempt to run Appium using an automation technology that is not supported for the version of Android.

Setting the `automationName` capability to `'UiAutomator'` ought to work.

**Comment by mindarchitect** [comment]
According to this
http://appium.io/docs/en/writing-running-appium/caps/index.html
There is no such automator as 'UiAutomator'.
And when trying to run with this automator it says
Original error: Could not find a driver for automationName 'UiAutomator' and platformName 'Android'. Please check your desired capabilities.
And in version 1.13 it was working with 'Appium' automator...
...
I have this overall feeling that latest versions are a bit bugy....

**Comment by imurchie** [comment]
My apologies. The correct `automationName` is `'UiAutomator1'`. 

The default for Android was changed in Appium version [1.13.0](https://github.com/appium/appium/releases/tag/v1.13.0)

**Comment by mindarchitect** [comment]
Now it runs. Thank you all for help. 
Update documentation please because this was exactly the case: I updated from 1.13 to 1.15 and tests stop to run because you just changed the automator name without any meaningful release notes...

Good luck!

**Comment by imurchie** [comment]
I feel like it couldn't really get clearer in the release notes. https://github.com/appium/appium/releases/tag/v1.14.0

The documentation ought to be updated, I agree.

**Pull request merged**
