### PR TITLE
Add support for getting element rect endpoint

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
See https://github.com/appium/appium-uiautomator2-server/commit/46f0e8c7714b814836b4387ca82fa4a32942f348

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I dunno why, but we had the same problem with element/:id:/name endpoint - it didn't work properly for the clients until I excluded it from proxy list.

**Comment by imurchie** [comment]
Strange. I just tried it locally it and it worked fine.
```
info HTTP --> GET /wd/hub/session/addfe2bb-dc6a-40bd-9170-79b31f8c2a53/element/1a2b3a40-ad08-494e-aa6d-73f7e0e0056d/rect {}
info MJSONWP Driver proxy active, passing request on via HTTP proxy
dbug JSONWP Proxy Proxying [GET /wd/hub/session/addfe2bb-dc6a-40bd-9170-79b31f8c2a53/element/1a2b3a40-ad08-494e-aa6d-73f7e0e0056d/rect] to [GET http://localhost:8200/wd/hub/session/85eb2b4f-dbfe-43ae-b8ae-1658097bee5e/element/1a2b3a40-ad08-494e-aa6d-73f7e0e0056d/rect] with body: {}
dbug JSONWP Proxy Got response with status 200: "{\"sessionId\":\"85eb2b4f-dbfe-43ae-b8ae-1658097bee5e\",\"status\":0,\"value\":{\"x\":0,\"y\":978,\"width\":1440,\"height\":158}}"
info JSONWP Proxy Replacing sessionId 85eb2b4f-dbfe-43ae-b8ae-1658097bee5e with addfe2bb-dc6a-40bd-9170-79b31f8c2a53
info HTTP <-- GET /wd/hub/session/addfe2bb-dc6a-40bd-9170-79b31f8c2a53/element/1a2b3a40-ad08-494e-aa6d-73f7e0e0056d/rect 200 65 ms - 113
```

**Comment by mykola-mokhnach** [comment]
Thanks for trying. Then we can close this PR %).

**Comment by imurchie** [comment]
Once https://github.com/appium/appium-uiautomator2-driver/pull/103 gets in, and `el.rect()` is added to [wd](https://github.com/admc/wd) we can add a test for this functionality.

**Pull request closed without merging**
