### PR TITLE
ci: fix keyboard-e2e-specs

### PR DESCRIPTION
**Pull request by rerorero**
I think this is the last part of https://github.com/appium/appium/issues/16402

This PR enables specs under test/functional/commands/keyboard  on CI

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
Do failed e2e tests have anything to do with the changes in this PR?

**Comment by rerorero** [comment]
right, they don't have anything to do with the changes.
I noticed E2E api-25 is always failing in some specific cases. I'll look at it later and may let them skip for api-25.

**Comment by mykola-mokhnach** [comment]
> right, they don't have anything to do with the changes.
> I noticed E2E test with api-25 is always failing in some specific test cases. I'll look at it later and may let them skip for api-25.

Thanks. Yep, lets skip unstable tests for now and then rebase to make sure there are no more false positives

**Comment by rerorero** [comment]
>  lets skip unstable tests for now

I prepared the PR https://github.com/appium/appium-uiautomator2-driver/pull/598, PTAL!

**Comment by rerorero** [comment]
I rebased the branch. E2E test for api28 failed but it's not related to this PR and probably rerun would fix it.

**Pull request merged**
