### PR TITLE
get session details from the uiauto2 server now that it has them

### PR DESCRIPTION
**Pull request by jlipps**
expose the accessibility scroll data from https://github.com/appium/appium-uiautomator2-server/pull/119 (though this can be merged in advance of that one, doesn't matter)

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
It looks like some tests got broken now

**Comment by jlipps** [comment]
@mykola-mokhnach that is actually a pre-existing bug in the server which will be fixed by the server PR i mentioned above. we can wait to merge that one to double-check here though.

**Comment by jlipps** [comment]
restarted travis build now that dependent PR has been merged/published.

**Comment by jlipps** [comment]
@mykola-mokhnach the travis run passed now (i just reran the `pr` version).

**Comment by jlipps** [comment]
published in 1.4.0

**Pull request merged**
