### PR TITLE
ci: use GH Action for detecting LTS Node

### PR DESCRIPTION
**Pull request by eglitise**
Same as https://github.com/appium/appium/pull/20059.
Also adjusted unit tests to be skipped for Markdown file changes.

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by mykola-mokhnach** [comment]
It looks like functional tests don't work anymore. Could you please try also bumping the java version there to 17?

**Comment by eglitise** [comment]
Seems like the architecture also needs to be changed? Unsure...

**Comment by mykola-mokhnach** [comment]
>   PANIC: Avd's CPU Architecture 'x86' is not supported by the QEMU2 emulator on aarch64 host.

Yes, looks like GH switched to use ARM runners now. This should be good news through - they should perform much better than intel ones

**Comment by mykola-mokhnach** [comment]
Or maybe we can switch to KVM runners: https://github.com/ReactiveCircus/android-emulator-runner?tab=readme-ov-file#running-hardware-accelerated-emulators-on-linux-runners

**Comment by mykola-mokhnach** [comment]
Actually we may try to copy the related changes from https://github.com/appium/appium-uiautomator2-driver/actions/runs/8919253215/job/24495129792?pr=770

**Comment by eglitise** [comment]
In that case maybe it's better if I revert the functional test changes in this PR, so they can be done entirely in Kazu's PR? Same for the Espresso driver PR.

**Review by KazuCocoa — APPROVED** [review]

**Pull request merged**
