### PR TITLE
Fix getting element's tag name

### PR DESCRIPTION
**Pull request by mykola-mokhnach**
Addresses https://github.com/appium/appium/issues/8644

### CODE REVIEW

**Comment by dpgraham** [comment]
@sravanmedarapu or @imurchie Can one of you two review this too? I'd like to publish this fix, as it looks like it's affecting a few people.

**Comment by dpgraham** [comment]
Published as patch 0.3.4

https://www.npmjs.com/package/appium-uiautomator2-driver

**Comment by crazyk2** [comment]
@dpgraham  how to make appium work with new patch version 0.3.4?
I installed via `npm install -g appium-uiautomator2-driver@0.3.4`, but when I start appium it get latest own version 0.3.3

**Comment by imurchie** [comment]
You need to install Appium as a whole. Installing the driver will not install it within Appium.

```
npm uninstall -g appium
npm cache clean
npm install -g appium@beta
```

**Pull request merged**
