### PR TITLE
fix: explicit eslint deps no longer required now that we have eslint-config-appium

### LINKED ISSUE #495: npm install fails due to dep resolution
On a fresh checkout, we get this:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: appium-uiautomator2-driver@2.0.0
npm ERR! Found: eslint-plugin-promise@6.0.0
npm ERR! node_modules/eslint-plugin-promise
npm ERR!   dev eslint-plugin-promise@"^6.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-promise@"5.2.0" from @appium/eslint-config-appium@5.0.1
npm ERR! node_modules/@appium/eslint-config-appium
npm ERR!   dev @appium/eslint-config-appium@"^5.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/jlipps/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jlipps/.npm/_logs/2022-01-24T17_16_32_466Z-debug.log
```

### PR DESCRIPTION
**Pull request by jlipps**
fixes #495

### CODE REVIEW

**Comment by mykola-mokhnach** [comment]
I don't quite understand how this deps resolution is supposed to work. In my case it was complaining about undersolved peer dependencies while executing `npm i`

**Review by mykola-mokhnach — APPROVED** [review]

**Comment by jlipps** [comment]
ok, what version of NPM were you running? I'm on 8.1.2

**Comment by mykola-mokhnach** [comment]
v6.14.15

**Comment by jlipps** [comment]
two major versions apart, i bet there's incompatible behaviour there. seems like we shouldn't break on latest npm so maybe it's time to retire support for npm 6?

**Pull request merged**
