### PR TITLE
use appium-base-driver instead of jsonwp/express/etc

### PR DESCRIPTION
**Pull request by jlipps**
@anandsadu @imurchie please review. these other modules are going away and we need to use basedriver.

### CODE REVIEW

**Comment by imurchie** [comment]
Looks good to me.

**Comment by bootstraponline** [comment]
> This branch has conflicts that must be resolved

**Comment by jlipps** [comment]
will rebase

**Comment by jlipps** [comment]
@anandsadu @bootstraponline this is merged but I don't have publish rights to `appium-uiautomator2-driver-test-1`; seems like this is a test package so maybe a publish isn't necessary?

**Comment by sravanmedarapu** [comment]
@jlipps Yes, appium-uiautomator2-driver-test-1 is a test package. we are using it for temporary purpose for testing, between I have added you to collaborators.

**Comment by jlipps** [comment]
ok, published as 1.2.51

**Comment by anandsadu** [comment]
@jlipps  : we can rename appium-uiautomator2-driver-test-1 to appium-uiautomator2-driver and publish once again.

**Pull request merged**
